# English text for the content audit (same observations as content_findings.py, same order).
# Keys: (link ID, observation number). Quotes, severities and register IDs come from
# content_findings.py; build_report_en.py asserts that the two files stay aligned.

PURPOSE = {
 "C01": "General introduction to the University for prospective students",
 "C02": "List of undergraduate and graduate programmes, with availability for male and female students",
 "C03": "Admission dates for the current intake",
 "C04": "Contact with the Admissions Office",
 "C05": "Enquiry form for applicants",
 "C06": "Apply button (Future Students)",
 "C07": "Admission of international students without Saudi residence (freshman, transfer, visiting, graduate, fees, housing)",
 "C08": "Apply button (International Students' Office)",
 "C09": "Graduate admissions home and programme list",
 "C10": "Admission requirements: PhD in Mechanical Engineering",
 "C11": "Admission requirements: PhD in Business Administration",
 "C12": "Admission requirements: Executive MBA",
 "C13": "Admission requirements: MBA",
 "C14": "Admission requirements: MS in Human Development",
 "C15": "Admission requirements: MS in Mechanical Engineering",
 "C16": "Admission requirements: MS in Electrical Engineering",
 "C17": "Admission requirements: MS in Civil Engineering",
 "C18": "Admission requirements: MS in Interior Design",
 "C19": "Admission requirements: MS in Engineering Management (EMGMS)",
 "C20": "Admission requirements: MA in International Business Law",
 "C21": "Graduate tuition and fees",
 "C22": "Graduate admissions contact",
 "C23": "Undergraduate admissions home",
 "C24": "Admission to the College of Medicine",
 "C25": "Admission to the Preparatory Program",
 "C26": "Direct admission from secondary school",
 "C27": "Transfer admission from another university",
 "C28": "Visiting-student admission",
 "C29": "Progression from the Preparatory Program to degree programmes",
 "C30": "Specific requirements for Computer Science and Engineering majors",
 "C31": "Undergraduate fees (index page)",
 "C32": "Overview of English-language tests",
 "C33": "Aptis placement test",
 "C34": "IELTS requirements",
 "C35": "TOEFL iBT requirements",
 "C36": "SAT requirements",
}

DATA = {
 "C01": ["No admission data; links to undergraduate and graduate admissions"],
 "C02": ["Undergraduate programmes in five colleges (Architecture & Design, Engineering, Computer Engineering & Science, Business Administration, Law)", "Graduate programmes in Engineering, Business Administration, Sciences & Human Studies, Architecture & Design and Law"],
 "C03": ["Fall 2026-2027 (undergraduate and graduate)", "First day of classes: 2026-08-30", "Saudi applicants via Qabool; non-Saudi applicants via Study in Saudi (marked Closed)"],
 "C04": ["Opens a staff list with personal names (not reproduced)"],
 "C05": ["Fields: name, email, mobile, query, preferred contact method"],
 "C06": ["Opens the application portal (admissions.pmu.edu.sa)"],
 "C07": ["Freshman: secondary GPA 80%, SAT I, IELTS 6.0 (5.5 writing), online interview", "Application fee: SAR 950 incl. VAT (freshman); SAR 500 excl. VAT (transfer and visiting)"],
 "C08": ["Opens the same general application portal"],
 "C09": ["Ten programmes, each with 'Application Form' and 'Admissions Requirements' entries"],
 "C10": ["Bachelor's and master's in Mechanical Engineering", "GPA 3.00/4.00", "IELTS 6.0 (5.5 each skill) or TOEFL iBT 83 (19 each)", "Two references, statement of purpose, interview"],
 "C11": ["Two tracks: Management and Finance", "Master's in Business Administration, Finance or a related field", "Three recommendation letters"],
 "C12": ["33 credit hours over two years, weekend delivery", "GPA 2.50", "Three to five years' experience", "Employer letter and three references"],
 "C13": ["36 credit hours, evening delivery, six concentrations", "GPA 2.50", "IELTS 6.0 or TOEFL iBT 83"],
 "C14": ["Relevant bachelor's degree with GPA 2.50", "Two references, statement of purpose, interview"],
 "C15": ["Minimum 30 credit hours, two tracks, thesis or non-thesis", "GPA 2.50", "Two references"],
 "C16": ["Two tracks", "Bachelor's in any engineering discipline", "GPA 2.50"],
 "C17": ["Two tracks", "Bachelor's in Civil Engineering", "GPA 2.50"],
 "C18": ["Bachelor's in Interior Design", "GPA 2.50"],
 "C19": ["GPA 3.00", "IELTS 7 / TOEFL iBT 79 / PTE 60"],
 "C20": ["Thesis and non-thesis tracks", "Bachelor's in Law with a 'Very Good' grade", "IELTS 6.5", "Weights: GPA 50%, written test 30%, interview 20%"],
 "C21": ["13 programmes priced in total and per credit hour, for PMU alumni and others", "VAT: 15% on tuition and fees for non-Saudi students; Saudi students pay VAT on fees only"],
 "C22": ["Graduate Study Admission Coordinator, office G-017, graduateadm@pmu.edu.sa"],
 "C23": ["Secondary GPA 80% and Qudrat 60% (or SAT 1)", "60/40 weighting for lower scores", "Application fee SAR 950 incl. VAT", "Day students up to 20 credits; evening students up to 12"],
 "C24": ["Seven-year programme", "Composite: (20% secondary + 40% Qudrat + 40% Tahseely) × 60% + interview 40%; minimum 86", "Minimums: secondary 95%, Qudrat 80, Tahseely 80", "Application fee SAR 1000 incl. VAT"],
 "C25": ["Secondary GPA 80% and Qudrat 60%", "Aptis placement test and interview", "Application fee SAR 950 incl. VAT", "Study-skills courses by English level"],
 "C26": ["Secondary GPA 80%, Qudrat 60%, IELTS 6.0 (5.5 writing)", "60/40 weighting"],
 "C27": ["Cumulative GPA 2.0/4.0", "Last course passed within five years", "Credit-transfer review of at least five weeks", "Application fee SAR 950 incl. VAT"],
 "C28": ["Home-institution approval and college approval", "Application fee SAR 950 incl. VAT"],
 "C29": ["Complete the Preparatory Program, pass the EXIT exam, meet college requirements", "Mathematics courses by college"],
 "C30": ["General: secondary ≥80 (60%) + Qudrat ≥60 (40%)", "Specific: secondary ≥85 (40%) + Qudrat ≥65 (30%) + Tahseely ≥65 (30%)", "SAT 1 (1200) as the Tahseely alternative"],
 "C31": ["Links to Medical Program fees, Fall 2026/2027, Fall 2025/2026 and Continuing Students 2024–2025"],
 "C32": ["Aptis for placement; IELTS and TOEFL for exemption"],
 "C33": ["Test duration about four hours", "Four placement levels"],
 "C34": ["Core 6.0/5.5; Advanced 5.0/4.5; Intermediate 4.5/4.0; Beginner 4.0/3.5", "Valid for two years to the start of the applied semester"],
 "C35": ["Core 83/19; Advanced 63/15; Intermediate 54/13; Beginner 42/11", "ETS institution code 6993"],
 "C36": ["SAT 1200 instead of Qudrat and Tahseely for international certificates", "Mathematics course waivers by SAT Math score", "College Board code 7647"],
}

VERIFIED = {
 "C21": ["Arithmetic check: total price = rate per credit hour × credit hours for EMBA (33), MBA (36), PhD (72), MSME/MSEE/MSCE/MSID (30), EMGMS (30), M.Eng (33) and MA IBL (36) — consistent."],
 "C34": ["Consistent with C26 and C07 (IELTS 6.0 overall, 5.5 writing for direct entry)."],
 "C35": ["The ETS code (6993) was not verified against an ETS source; confirmation is recommended."],
}

ISSUES = {
 ("C01", 1): ("Numerical claims carry no date or source, and the phrase 'accredited by prestigious national and international organizations' names no accrediting body.", "Name each accreditation (body, scope, date) or remove unsourced figures."),
 ("C02", 1): ("The list omits the College of Medicine and the College of Sciences and Human Studies (undergraduate), while it adds programmes (Chemical Engineering, Cybersecurity) that the major-specific requirement pages (C30, C36) do not mention.", "Publish one programme list from a single programme register, with admission status per programme."),
 ("C02", 2): ("The programmes sit inside two collapsed lists; a visitor initially sees two headings only. The page code also keeps a hidden 'Master of LAW' entry.", "Show the list openly, with each programme linked to its requirements; remove leftover code."),
 ("C03", 1): ("On the audit date (28 September 2026) every date of the published intake has passed, and there is no information on the next intake or on whether admission is open.", "Add an 'admission status now' component and the next intake's dates, or state explicitly that admission is closed until a given date."),
 ("C03", 2): ("Results are announced from 19 July, before the 20 July deadline for IELTS/TOEFL scores and for transfer documents.", "Re-sequence the dates or state which applicant groups the early results cover."),
 ("C03", 3): ("The calendar states that non-Saudi applications via Study in Saudi are 'Closed', while C07 states that international applicants apply entirely online through the PMU portal.", "Define one channel per applicant category and show it identically on both pages."),
 ("C03", 4): ("Orientation is still 'TBA' although classes have started.", "Update or remove the entry once it has passed."),
 ("C04", 1): ("The target gives no Admissions Office telephone number, shared mailbox or office hours; applicants are directed to named individuals.", "Link to a single admissions contact page (role mailbox, telephone, hours, enquiry form)."),
 ("C05", 1): ("Spelling errors in four Arabic labels and one English label of the form (published and correct spellings are listed in the table below).", "Proof-read both languages and apply the corrections."),
 ("C05", 2): ("The form states no expected response time and offers no direct alternative channel.", "State the service standard and link the admissions contact component."),
 ("C06", 1): ("'Apply Now' sends every applicant to the same portal, while the calendar (C03) sends Saudi applicants to Qabool and non-Saudi applicants to Study in Saudi — three channels for one step.", "Replace the button with an application router by applicant category."),
 ("C07", 1): ("The application fee for international transfer and visiting students is SAR 500 excluding VAT, while C27 (transfer) and C28 (visiting) state SAR 950 including VAT for the same applicants.", "Finance to confirm one fee per category, published from the fee record."),
 ("C07", 2): ("SAT II (Subject Tests) is required for Engineering and Computer Science; College Board discontinued these tests internationally in 2021.", "Replace with the approved requirement (Tahseely or its approved equivalent)."),
 ("C07", 3): ("A 'National ID' is requested from an international applicant without Saudi residence — a document such applicants do not hold.", "Request the passport only."),
 ("C07", 4): ("No minimum SAT I score is stated, whereas the SAT page (C36) sets 1200.", "State the numerical minimum."),
 ("C07", 5): ("The graduate section for international applicants lists three programmes, out of eleven linked from the Admissions Office page.", "Link to the full programme list and state which programmes accept international applicants."),
 ("C07", 6): ("The 'Transportation' section is a heading without content, and the housing text is written in the future tense ('will be located').", "Publish current transport and housing information."),
 ("C07", 7): ("Payment instructions for international students exist in the page code but are not displayed (not reproduced here because they contain bank details).", "Decide whether to publish the official payment method; remove leftover code."),
 ("C08", 1): ("The button does not indicate the correct channel for non-residents, whose channel the calendar marks as 'Closed'.", "As for C06."),
 ("C09", 1): ("The list omits EMGMS (linked from the Admissions Office page as C19 and priced in C21) and the Master of Engineering in Innovation, Sustainability, and Entrepreneurship priced in C21.", "Generate the list from the programme register."),
 ("C09", 2): ("Programme names differ between pages: 'Master of Human Development' here, 'MSHD' on the Admissions Office page, 'Master of Science in Human Development' in C14 and 'Master of Science in Education and Human Development' in C21; 'Doctorate' here, 'PhD' in C10 and 'Doctoral program' in C21.", "Adopt one official name per programme, in Arabic and English."),
 ("C09", 3): ("MSCE, MSEE and MSID show 'Application Form' without a link, while the other programmes have one.", "Provide a working form link for every programme."),
 ("C10", 1): ("The descriptor 'Very Good' is attached here to 3.00, and on six other pages to 2.50.", "Registrar to publish one grade-conversion table."),
 ("C10", 2): ("The page states no credit hours, duration, fees or deadlines (C21 gives 72 credits and SAR 150,000).", "Add a 'programme facts' block."),
 ("C11", 1): ("A double negative reverses the intended meaning (the intended condition is a master's degree from another discipline), and it is unclear to whom each GPA condition (3.00 or 3.20) applies.", "Rewrite the rule as a table: background → bridging courses → minimum GPA."),
 ("C11", 2): ("AACSB accredits business schools (institution level), not individual programmes, and 'fewer than 6%' describes the share of accredited schools, not a ranking ('top').", "Use precise wording once the College confirms: 'The College of Business Administration holds AACSB accreditation, held by fewer than 6% of business schools worldwide.'"),
 ("C12", 1): ("2.50 is described as 'Very Good', while 3.00 carries the same descriptor in C10.", "One grade-conversion table."),
 ("C12", 2): ("Experience is 'from three to five years' (are candidates with six or more years excluded?) but 'several years' in the same page.", "State 'at least three years'."),
 ("C13", 1): ("As for C12.", "One grade-conversion table."),
 ("C13", 2): ("No supporting documents are listed (references, statement, CV), unlike every other graduate programme; it should be confirmed that none are required.", "College to confirm the document list."),
 ("C14", 1): ("A 'Work Experience' heading has no requirement under it (the CV item follows directly).", "State the experience requirement or remove the heading."),
 ("C14", 2): ("No credit hours or duration are stated (the fee table in C21 implies 42 credits: 50,000 ÷ 1,191).", "Add a 'programme facts' block."),
 ("C15", 1): ("As for C12.", "One grade-conversion table."),
 ("C16", 1): ("'will be offered' suggests the programme has not launched — is it open for admission?", "Show programme status (open / not open) and update the wording."),
 ("C16", 2): ("As for C12.", "One grade-conversion table."),
 ("C17", 1): ("As for C16.", "As for C16."),
 ("C17", 2): ("As for C12.", "One grade-conversion table."),
 ("C18", 1): ("The whole introduction is in the future tense ('will educate', 'will be to provide').", "Update the wording."),
 ("C18", 2): ("As for C12.", "One grade-conversion table."),
 ("C19", 1): ("Content copied from another university (University of Arizona); a pathway that does not apply to PMU applicants.", "Withdraw the page and rewrite it from PMU's requirements."),
 ("C19", 2): ("IELTS 7 is higher than every other PMU programme (6.0) while TOEFL 79 is lower (83) — the equivalence contradicts itself within the page.", "Adopt PMU's single graduate threshold."),
 ("C19", 3): ("No programme description, duration or interview, unlike every other graduate programme.", "Use the standard programme-page template."),
 ("C20", 1): ("The programme has 36 credits (C21); a maximum of 6 credits per semester means six semesters (three years), not two years.", "Correct the duration or the per-semester maximum."),
 ("C20", 2): ("A 30% weight is given to a 'written test' that is neither listed among the admission criteria nor described.", "Describe the test (content, date, minimum score)."),
 ("C20", 3): ("IELTS 6.5 is paired with TOEFL iBT 83, whereas TOEFL 83 is paired with IELTS 6.0 in the other programmes.", "One concordance table."),
 ("C20", 4): ("The 'Very Good' grade has no numerical value (other programmes state a number).", "State the numerical GPA."),
 ("C20", 5): ("A statement tied to the year 2025.", "Use time-independent wording."),
 ("C21", 1): ("Two priced programmes have no admission page among the 36 links.", "Add admission pages or remove the rows if the programmes are not open."),
 ("C21", 2): ("The same programme appears under two names in the two tables.", "One official name."),
 ("C22", 1): ("Only an email address and an office number; no telephone or office hours.", "Single admissions contact component."),
 ("C23", 1): ("Lists five colleges only, omitting the College of Medicine (described on the same page) and the College of Sciences and Human Studies.", "Generate the list of colleges from the programme register."),
 ("C23", 2): ("'College of Medical' is incorrect (College of Medicine).", "Correct."),
 ("C23", 3): ("Here visiting students come from 'local or international' universities; C07 says 'international' only. It should be clear whether local visiting students are accepted.", "One definition."),
 ("C24", 1): ("An applicant who meets every published minimum (95/80/80) scores 83, below the stated minimum of 86.", "Publish consistent minimums or a worked example."),
 ("C24", 2): ("The programme is described as seven years, but the curriculum shown stops at Year 6, and the College's academic page states six years.", "College to confirm the duration and publish the total cost."),
 ("C24", 3): ("Unedited draft text (generic explanatory style) and 'to be developed' placeholders.", "Rewrite the page."),
 ("C24", 4): ("Years 1–2 are described as a list of US-style prerequisites, not as a PMU study plan.", "Describe the curriculum as actually taught."),
 ("C24", 5): ("The page states neither the English requirement, nor the SAR 20,000 non-refundable seat reservation, nor the programme cost.", "Add complete requirements and a cost block."),
 ("C24", 6): ("The Medicine application fee is SAR 1000 here and SAR 1,150 on the Medicine fees page.", "One value from Finance."),
 ("C25", 1): ("Content is broadly sound; the duration and cost of the Preparatory Program are not stated.", "Add duration and cost."),
 ("C26", 1): ("Only a 'Saudi ID' is requested, without the Iqama option available on the Preparatory and Transfer pages — non-Saudi residents cannot see themselves in this route.", "'National ID or Iqama'."),
 ("C26", 2): ("The required TOEFL score is not stated on the page (it is in C35: 83/19).", "State the number in place."),
 ("C27", 1): ("SAR 950 including VAT here, and SAR 500 excluding VAT on the international page (C07).", "One value per category."),
 ("C27", 2): ("Grammatical error ('to be consider').", "Correct to 'considered'."),
 ("C28", 1): ("SAR 950 including VAT here, and SAR 500 excluding VAT in C07.", "One value per category."),
 ("C28", 2): ("A visiting university student is asked for a secondary-school certificate and an aptitude test — necessity should be confirmed.", "Review the document list."),
 ("C29", 1): ("Footnote markers are swapped: (*) sits on Engineering and Architecture but concerns Information Technology; (**) sits on Computer Engineering & Science but concerns Architecture.", "Correct the footnotes."),
 ("C29", 2): ("The 'EXIT exam' is not defined (content and passing standard).", "Define the exam."),
 ("C30", 1): ("Seven majors carry specific requirements here; the SAT page (C36) adds 'Artificial Intelligence … etc.', and the programme list (C02) includes Chemical Engineering and Cybersecurity without stating their requirements.", "One closed list of majors with specific requirements."),
 ("C30", 2): ("The minimum weighted total is not published.", "Publish the number or state that it varies by intake."),
 ("C30", 3): ("The Tahseely alternative is SAT 1200 here and 1300 on the Medicine page.", "Set the official equivalence."),
 ("C30", 4): ("'wave' should read 'waive'.", "Correct."),
 ("C31", 1): ("Three generations of fee schedules are shown with no indication of which is current.", "One current schedule plus a clearly labelled archive."),
 ("C32", 1): ("'PMU recognized' is undefined; the page names only IELTS and TOEFL while C19 accepts PTE.", "Publish the list of recognised tests."),
 ("C33", 1): ("No Aptis score bands are published for the placement levels, whereas IELTS and TOEFL have published tables.", "Publish the Aptis score table."),
 ("C33", 2): ("'Core Program' is undefined (other pages say 'degree program').", "Use one term."),
 ("C35", 1): ("The table uses the 0–120 scale only. Since 21 January 2026 ETS reports TOEFL iBT on a 1–6 band scale; the comparable 0–120 score is shown only through January 2028. The page gives no 1–6 thresholds.", "Add the new-scale column once the concordance is approved."),
 ("C36", 1): ("An open list ('etc.') that differs from C30.", "One closed list."),
 ("C36", 2): ("1200 replaces both tests here; 1300 replaces Tahseely on the Medicine page; C07 requires SAT I and SAT II.", "One SAT rule per applicant category."),
 ("C36", 3): ("'Wave' should read 'Waive'.", "Correct."),
}

MATRIX = [
 ("Application fee", [("C23, C25, C26, C27, C28, C30", "SAR 950 (incl. VAT)"), ("C24 (Medicine)", "SAR 1000 (incl. VAT)"), ("C07 (international transfer/visiting)", "SAR 500 (excl. VAT)")]),
 ("GPA descriptor 'Very Good'", [("C12, C13, C15, C16, C17, C18", "2.50 / 4.00"), ("C10", "3.00 / 4.00"), ("C20", "no number")]),
 ("English — graduate", [("Nine programmes", "IELTS 6.0 (5.5 each skill) or TOEFL iBT 83 (19)"), ("C20 MA IBL", "IELTS 6.5 or TOEFL iBT 83"), ("C19 EMGMS", "IELTS 7, TOEFL iBT 79, PTE 60 or CESL")]),
 ("SAT alternative", [("C36", "1200 instead of Qudrat and Tahseely"), ("C30", "SAT 1 (1200) instead of Tahseely"), ("C24", "SAT 1 1300 instead of Tahseely"), ("C07", "SAT I + SAT II")]),
 ("Identity document", [("C26, C30", "Saudi ID only"), ("C24, C25, C27, C28", "Saudi ID or Iqama"), ("C07", "National ID for an applicant without residence")]),
 ("Majors with specific requirements", [("C30", "seven majors"), ("C36", "eight + 'etc.'"), ("C02", "Chemical Engineering and Cybersecurity listed, requirements not stated")]),
 ("Application channel", [("C03", "Qabool (Saudi) / Study in Saudi — Closed (non-Saudi)"), ("C06, C08", "PMU portal for all"), ("C07", "'completed entirely online'")]),
 ("Graduate programme names", [("C09", "Master of Human Development · Doctorate in ME"), ("C14", "Master of Science in Human Development"), ("C21", "… Education and Human Development · Doctoral program")]),
 ("Graduate programme list", [("Admissions Office page", "11 links"), ("C09", "10 — without EMGMS"), ("C21", "12 + Pre-Master"), ("C07", "3 for international applicants")]),
]

GROUPS = {"Future Students": "Future Students", "International Students’ Office": "International Students’ Office",
          "Graduate Admissions": "Graduate Admissions", "Undergraduate Admissions": "Undergraduate Admissions",
          "Undergraduate Placement Tests": "Undergraduate Placement Tests"}

KIND = {"conflict": "Cross-page conflict", "error": "Incorrect information", "gap": "Missing information",
        "stale": "Out of date", "wording": "Wording / language", "claim": "Claim requiring verification"}

SITEMAP_EN = {"home": "Admissions (home)", "ug": "Undergraduate", "ug_hs": "High-school graduate in KSA", "ug_intl": "International (no Saudi residence)",
              "ug_transfer": "Transfer", "ug_med": "College of Medicine", "ug_prep": "Preparatory Program", "ug_visit": "Visiting student",
              "grad": "Graduate", "grad_prog": "Programme page (one template × 11)", "req": "English & tests", "costs": "Costs & scholarships",
              "dates": "Dates & cycle status", "apply": "Apply now (channel router)", "programs": "Programme finder", "contact": "Contact & enquiries",
              "archive": "Archive (not indexed)"}

# Published → correct spelling, shown as a table (keeps Arabic out of English running text)
SPELLING = {("C05", 1): [("الأسم", "الاسم"), ("إستفساراتكم", "استفساراتكم"), ("الإستفسار", "الاستفسار"), ("الإللكتروني", "الإلكتروني"), ("Verifaction", "Verification")]}
